jobs:
- sparkJob:
    args:
    - 'gs://xyz-sp2'
    - 'ibrd-statement-of-loans-latest-available-snapshot.csv'
    - 'ibrd-large-spark'
    jarFileUris:
    - gs://xyz-sp2/dataprocJavaDemo-1.0-SNAPSHOT.jar
    mainClass: org.example.dataproc.InternationalLoansAppDataproc
  stepId: ibrd-large-spark
placement:
  managedCluster:
    clusterName: sparkcluster2
    config:
      gceClusterConfig:
        # zoneUri: us-central1-f
        zoneUri: ''
        subnetworkUri: https://www.googleapis.com/compute/v1/projects/xyz-hostproject1/regions/us-central1/subnetworks/subnet-us-central1
        tags:
          - central
          - anothertag
      masterConfig:
        diskConfig:
          bootDiskSizeGb: 50
        machineTypeUri: n1-standard-4
      softwareConfig:
        imageVersion: 1.3-deb9
      workerConfig:
        diskConfig:
          bootDiskSizeGb: 50
        machineTypeUri: n1-standard-4
        numInstances: 2
      secondaryWorkerConfig:
        numInstances: 1
